### ISSUE TITLE
e_sqlite3.o

### ISSUE THREAD

**Issue by odyyudah** [dotnetnoobie/BlazorAppSqlite#2]
I tried to build your solution but here is the error message:

System.AggregateException: One or more errors occurred. (The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: e_sqlite3
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---

**Comment by ghost** [comment]
You need to install the WebAssembly build tools in VS22.

The easiest way to do that is just to go inside the VS installer, modify your installation and in the tab to select specific features search "Webassembly" and the option will appear in first.

The reason is that ```NativeFileReference``` in the csproj build native code into dlls. So if you do not have the tools to compile the native code to webassembly compatible code, of course you can't find the dll required.
